spring:
  datasource:
    url: jdbc:mysql://${DB_ENDPOINT}:3306/blog
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

  sql:
    init:
      mode: ${INIT_MODE}
      data-locations: classpath:db_migration.sql
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org:
      springframework:
        web: ${LOG_CONFIGURATION}
        security: DEBUG
        socket: TRACE
server:
  servlet:
    session:
      timeout: 60m
management:
  endpoints:
    web:
      exposure:
        include: ["health", "prometheus"]
  endpoint:
    beans:
      cache:
        time-to-live: 10s
